apiVersion: 1

datasources:
  - name: Kafka
    uid: kafka-local
    type: hamedkarbasi93-kafka-datasource
    access: proxy
    editable: true
    isDefault: true
    jsonData:
      bootstrapServers: kafka:29092
      securityProtocol: PLAINTEXT
